spring:
  data:
    mongodb:
      uri: mongodb+srv://dev:dev1234567890@cluster0.zddpw.mongodb.net/employeeDatabase?retryWrites=true&w=majority&appName=Cluster0
      database: employeeDatabase
      auto-index-creation: true
server:
  port: 8080