server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ems_app
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

